ID_PREFIX = "imvdb"
SITE_URL = "https://imvdb.com"
API_URL = "https://imvdb.com/api/v1"
COUNTRIES = {
    "United States": "us",
    "United Kingdom": "gb",
    "Angola": "ao",
    "Antigua And Barbuda": "ag",
    "Argentina": "ar",
    "Aruba": "aw",
    "Australia": "au",
    "Austria": "at",
    "Bahamas": "bs",
    "Barbados": "bb",
    "Belarus": "by",
    "Belgium": "be",
    "Bolivia": "bo",
    "Bosnia And Herzegowina": "ba",
    "Brazil": "br",
    "Bulgaria": "bg",
    "Canada": "ca",
    "Chile": "cl",
    "China": "cn",
    "Colombia": "co",
    "Costa Rica": "cr",
    "Croatia (Local Name: Hrvatska)": "hr",
    "Cuba": "cu",
    "Czech Republic": "cz",
    "Denmark": "dk",
    "Dominican Republic": "do",
    "Ecuador": "ec",
    "Egypt": "eg",
    "Estonia": "ee",
    "Finland": "fi",
    "France": "fr",
    "France, Metropolitan": "fx",
    "French Southern Territories": "tf",
    "Georgia": "ge",
    "Germany": "de",
    "Ghana": "gh",
    "Greece": "gr",
    "Hong Kong": "hk",
    "Hungary": "hu",
    "Iceland": "is",
    "India": "in",
    "Indonesia": "id",
    "Iran (Islamic Republic Of)": "ir",
    "Ireland": "ie",
    "Israel": "il",
    "Italy": "it",
    "Jamaica": "jm",
    "Japan": "jp",
    "Kenya": "ke",
    "Korea, Republic Of": "kr",
    "Latvia": "lv",
    "Lebanon": "lb",
    "Macau": "mo",
    "Macedonia, Former Yugoslav Republic Of": "mk",
    "Malaysia": "my",
    "Malta": "mt",
    "Martinique": "mq",
    "Mauritius": "mu",
    "Mexico": "mx",
    "Monaco": "mc",
    "Morocco": "ma",
    "Netherlands": "nl",
    "Netherlands Antilles": "an",
    "New Zealand": "nz",
    "Nigeria": "ng",
    "Norway": "no",
    "Panama": "pa",
    "Peru": "pe",
    "Philippines": "ph",
    "Poland": "pl",
    "Portugal": "pt",
    "Puerto Rico": "pr",
    "Qatar": "qa",
    "Romania": "ro",
    "Russian Federation": "ru",
    "Saint Lucia": "lc",
    "Senegal": "sn",
    "Serbia": "rs",
    "Slovakia (Slovak Republic)": "sk",
    "Slovenia": "si",
    "South Africa": "za",
    "Spain": "es",
    "Sri Lanka": "lk",
    "Sweden": "se",
    "Switzerland": "ch",
    "Taiwan": "tw",
    "Thailand": "th",
    "Trinidad And Tobago": "tt",
    "Tunisia": "tn",
    "Turkey": "tr",
    "Ukraine": "ua",
    "United Arab Emirates": "ae",
    "Uruguay": "uy",
    "Venezuela": "ve",
    "Yugoslavia": "yu",
    "Zimbabwe": "zw",
}
